// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerMCP.Data;

#nullable disable

namespace ServerMCP.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250921010217_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ServerMCP.Models.Beverage", b =>
                {
                    b.Property<int>("BeverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CaloriesPerServing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainIngredient")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("BeverageId");

                    b.ToTable("Beverages");

                    b.HasData(
                        new
                        {
                            BeverageId = 1,
                            CaloriesPerServing = 140,
                            MainIngredient = "Sugar",
                            Name = "Coca-Cola",
                            Origin = "United States",
                            Type = "Soft Drink"
                        },
                        new
                        {
                            BeverageId = 2,
                            CaloriesPerServing = 150,
                            MainIngredient = "Sugar",
                            Name = "Pepsi",
                            Origin = "United States",
                            Type = "Soft Drink"
                        },
                        new
                        {
                            BeverageId = 3,
                            CaloriesPerServing = 0,
                            MainIngredient = "Green Tea Leaves",
                            Name = "Green Tea",
                            Origin = "China",
                            Type = "Tea"
                        },
                        new
                        {
                            BeverageId = 4,
                            CaloriesPerServing = 5,
                            MainIngredient = "Coffee Beans",
                            Name = "Espresso",
                            Origin = "Italy",
                            Type = "Coffee"
                        },
                        new
                        {
                            BeverageId = 5,
                            CaloriesPerServing = 250,
                            MainIngredient = "Fruit",
                            Name = "Smoothie",
                            Origin = "United States",
                            Type = "Fruit Drink"
                        },
                        new
                        {
                            BeverageId = 6,
                            CaloriesPerServing = 245,
                            MainIngredient = "Coconut Cream",
                            Name = "Pina Colada",
                            Origin = "Puerto Rico",
                            Type = "Cocktail"
                        },
                        new
                        {
                            BeverageId = 7,
                            CaloriesPerServing = 120,
                            MainIngredient = "Lemon",
                            Name = "Lemonade",
                            Origin = "Ancient Egypt",
                            Type = "Soft Drink"
                        },
                        new
                        {
                            BeverageId = 8,
                            CaloriesPerServing = 350,
                            MainIngredient = "Milk",
                            Name = "Milkshake",
                            Origin = "United States",
                            Type = "Dairy Drink"
                        },
                        new
                        {
                            BeverageId = 9,
                            CaloriesPerServing = 150,
                            MainIngredient = "Black Tea Leaves and Spices",
                            Name = "Chai",
                            Origin = "India",
                            Type = "Tea"
                        },
                        new
                        {
                            BeverageId = 10,
                            CaloriesPerServing = 200,
                            MainIngredient = "Tequila",
                            Name = "Margarita",
                            Origin = "Mexico",
                            Type = "Cocktail"
                        },
                        new
                        {
                            BeverageId = 11,
                            CaloriesPerServing = 200,
                            MainIngredient = "Matcha Powder",
                            Name = "Matcha Latte",
                            Origin = "Japan",
                            Type = "Tea"
                        },
                        new
                        {
                            BeverageId = 12,
                            CaloriesPerServing = 0,
                            MainIngredient = "Carbonated Water",
                            Name = "Sparkling Water",
                            Origin = "Various",
                            Type = "Water"
                        },
                        new
                        {
                            BeverageId = 13,
                            CaloriesPerServing = 30,
                            MainIngredient = "Tea and Sugar",
                            Name = "Kombucha",
                            Origin = "China",
                            Type = "Fermented Tea"
                        },
                        new
                        {
                            BeverageId = 14,
                            CaloriesPerServing = 200,
                            MainIngredient = "Cocoa Beans",
                            Name = "Hot Chocolate",
                            Origin = "South America",
                            Type = "Hot Drink"
                        },
                        new
                        {
                            BeverageId = 15,
                            CaloriesPerServing = 125,
                            MainIngredient = "Grapes",
                            Name = "Red Wine",
                            Origin = "Various",
                            Type = "Alcoholic Drink"
                        },
                        new
                        {
                            BeverageId = 16,
                            CaloriesPerServing = 150,
                            MainIngredient = "Rum",
                            Name = "Mojito",
                            Origin = "Cuba",
                            Type = "Cocktail"
                        },
                        new
                        {
                            BeverageId = 17,
                            CaloriesPerServing = 120,
                            MainIngredient = "Ginger",
                            Name = "Ginger Ale",
                            Origin = "United States",
                            Type = "Soft Drink"
                        },
                        new
                        {
                            BeverageId = 18,
                            CaloriesPerServing = 5,
                            MainIngredient = "Coffee Beans",
                            Name = "Black Coffee",
                            Origin = "Ethiopia",
                            Type = "Coffee"
                        },
                        new
                        {
                            BeverageId = 19,
                            CaloriesPerServing = 0,
                            MainIngredient = "Chamomile Flowers",
                            Name = "Chamomile Tea",
                            Origin = "Egypt",
                            Type = "Herbal Tea"
                        },
                        new
                        {
                            BeverageId = 20,
                            CaloriesPerServing = 100,
                            MainIngredient = "Grain",
                            Name = "Whiskey",
                            Origin = "Ireland/Scotland",
                            Type = "Alcoholic Drink"
                        },
                        new
                        {
                            BeverageId = 21,
                            CaloriesPerServing = 60,
                            MainIngredient = "Coconut",
                            Name = "Coconut Water",
                            Origin = "Pacific Islands",
                            Type = "Water"
                        },
                        new
                        {
                            BeverageId = 22,
                            CaloriesPerServing = 160,
                            MainIngredient = "Sarsaparilla Root",
                            Name = "Root Beer",
                            Origin = "United States",
                            Type = "Soft Drink"
                        },
                        new
                        {
                            BeverageId = 23,
                            CaloriesPerServing = 90,
                            MainIngredient = "Black Tea Leaves",
                            Name = "Iced Tea",
                            Origin = "United States",
                            Type = "Cold Tea"
                        },
                        new
                        {
                            BeverageId = 24,
                            CaloriesPerServing = 190,
                            MainIngredient = "Coffee and Milk",
                            Name = "Latte",
                            Origin = "Italy",
                            Type = "Coffee"
                        },
                        new
                        {
                            BeverageId = 25,
                            CaloriesPerServing = 0,
                            MainIngredient = "Various Herbs",
                            Name = "Herbal Tea",
                            Origin = "Worldwide",
                            Type = "Tea"
                        },
                        new
                        {
                            BeverageId = 26,
                            CaloriesPerServing = 110,
                            MainIngredient = "Caffeine and Sugar",
                            Name = "Energy Drink",
                            Origin = "Worldwide",
                            Type = "Soft Drink"
                        },
                        new
                        {
                            BeverageId = 27,
                            CaloriesPerServing = 150,
                            MainIngredient = "Barley and Hops",
                            Name = "Beer",
                            Origin = "Various",
                            Type = "Alcoholic Drink"
                        },
                        new
                        {
                            BeverageId = 28,
                            CaloriesPerServing = 180,
                            MainIngredient = "Red Wine and Fruit",
                            Name = "Sangria",
                            Origin = "Spain",
                            Type = "Alcoholic Drink"
                        },
                        new
                        {
                            BeverageId = 29,
                            CaloriesPerServing = 60,
                            MainIngredient = "Milk or Plant-Based",
                            Name = "Probiotic Drink",
                            Origin = "Worldwide",
                            Type = "Fermented Drink"
                        },
                        new
                        {
                            BeverageId = 30,
                            CaloriesPerServing = 200,
                            MainIngredient = "Tea and Tapioca Pearls",
                            Name = "Bubble Tea",
                            Origin = "Taiwan",
                            Type = "Tea"
                        },
                        new
                        {
                            BeverageId = 31,
                            CaloriesPerServing = 210,
                            MainIngredient = "Apples",
                            Name = "Cider",
                            Origin = "United Kingdom",
                            Type = "Alcoholic Drink"
                        },
                        new
                        {
                            BeverageId = 32,
                            CaloriesPerServing = 130,
                            MainIngredient = "Quinine and Sugar",
                            Name = "Tonic Water",
                            Origin = "United Kingdom",
                            Type = "Soft Drink"
                        },
                        new
                        {
                            BeverageId = 33,
                            CaloriesPerServing = 2,
                            MainIngredient = "Coffee Beans (Decaffeinated)",
                            Name = "Decaf Coffee",
                            Origin = "Worldwide",
                            Type = "Coffee"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
